# Generated by Django 2.1.5 on 2019-01-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gimage',
            field=models.ImageField(default='default.png', upload_to='gimages/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='gtitle',
            field=models.CharField(default='作品标题', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='descrption',
            field=models.CharField(default='这里是默认描述', max_length=100),
        ),
    ]
